### ISSUE TITLE
Is generated SQL available?

### ISSUE THREAD

**Issue by bob-rietveld** [duckdblabs/duckplyr#132]
Hi, 

Thanks for your work on this package, it's super nice and fast! May be I missed it , but is there somewhere I can access the SQL statement that is being executed on duckdb ? Explain() provides the plan, but is it possible to get the SQL statement in a variable in R? Similar to show_query() in dbplyr (https://dbplyr.tidyverse.org/articles/sql.html) , is what I am looking for. Thanks.

**Comment by krlmlr** [comment]
duckplyr never generates SQL. Need to update the documentation to clarify this.

**Comment by krlmlr** [comment]
We use the "relational API" that is very similar to Codd's relational algebra. These functions are currently private in duckdb.

**Comment by bob-rietveld** [comment]
Aha, thanks for clarifying.
