### ISSUE TITLE
Document available functions

### ISSUE THREAD

**Issue by TimTaylor** [duckdblabs/duckplyr#135]
Currently it's not clear which functions are supported/available within the package.

As a concrete example, the functions `wday()` and `hour()` both work but, as they are not part of dplyr, their availability is not obvious.

**Comment by krlmlr** [comment]
A first step is to explicitly list the supported functions in the code: https://github.com/duckdblabs/duckplyr/pull/179/files#diff-a202cfba76540d6822868ac7755edd4945b6344057d78e0092f4836e33c0d4eaR11 . I'd like to extend this with a contributing guide, and with a way to supply custom translations for the local sessions. Feedback appreciated. Thanks!

**Comment by krlmlr** [comment]
Contributing guide done now.
