### ISSUE TITLE
Make description in DESCRIPTION longer

### ISSUE THREAD

**Issue by maelle** [duckdblabs/duckplyr#17]
Malformed Description field: should contain one or more complete sentences.

**Comment by maelle** [comment]
It'd be the occasion to fill in the goal of duckplyr in the README :smile_cat:

**Comment by krlmlr** [comment]
@hannes: can you please give Maëlle triaging rights to this repo?

@maelle: once done, can you please assign to me the issues that I need to handle?

**Comment by hannes** [comment]
Yes, sent invite

**Comment by maelle** [comment]
@hannes thank you!
