### ISSUE TITLE
Update documents in [Data ingestion]

### ISSUE THREAD

**Issue by jhk0530** [duckdblabs/duckplyr#173]
Hi, I'm trying `duckplyr` as an alternative to `dplyr`. 
and following with documents from pkgdown.

and I found some of the documentation could be improved.

in <a href='https://duckdblabs.github.io/duckplyr/reference/index.html#data-ingestion' target ='_blank'>**Reference**</a>

At now, documents shows like below.
```
`df_from_csv()` `duckplyr_df_from_csv()` `df_from_parquet()` `duckplyr_df_from_parquet()` `df_to_parquet()` `df_from_file()` `duckplyr_df_from_file()`
df_from_csv
```

but this may change as below.

```
`df_from_csv()`, `duckplyr_df_from_csv()`
- dataframes from csv
`df_from_parquet()`, `duckplyr_df_from_parquet()`
- dataframes from parquet
`df_to_parquet()`
- write dataframes to parquet
`df-from_file()`, `duckplyr_df_from_fle()`
- dataframes from json 
```

in files, I mentioned only **json** which is not sure, but I found only **json** in <a href='https://duckdb.org/docs/data/overview' target = "_blank">duckdb docs</a>

---

I think issue #135 tells there are many functions which is not documented yet, so this may not be prior task. but one of starting point with it.

Also this is another question, (not important) `duckplyr` supports parquet only as exporting result. 
If I wanted to save result as a CSV, could I simply use `write.csv()`? 

Thanks.

**Comment by krlmlr** [comment]
Thanks, Jinhwan, for raising this. I'll review when I next work on the documentation.
