### ISSUE TITLE
`df_from_parquet()` doesn't take a directory name?

### ISSUE THREAD

**Issue by hadley** [duckdblabs/duckplyr#181]
```
> logs <- duckplyr::df_from_parquet("logs/")
Error:
! {"exception_type":"IO","exception_message":"No files found that match the pattern \"logs/\""}
Show Traceback
```

But this is ok:

```
logs <- duckplyr::df_from_parquet(dir("logs/", full.names = TRUE))
```

**Comment by hadley** [comment]
Oh but that second one only reads a single data frame.

**Comment by hadley** [comment]
But even when I get it working it's basically unusable. I'll try find some time to show @krlmlr in person next week.

**Comment by krlmlr** [comment]
Does `bind_rows()` give you a better experience? See #146.

**Comment by krlmlr** [comment]
`bind_rows()` reads into memory, `%>% reduce(union_all)` is better but will also read into memory in duckplyr 0.4.0 (works better in duckplyr 0.3.0): https://github.com/tidyverse/dplyr/pull/7049 .

What *should* work is `duckplyr_df_from_csv("file_*.csv")`, but I'm seeing mixed results too: https://github.com/duckdb/duckdb/issues/12903 .

Action items:

- Check that `path` is a scalar
- Fix `union_all()` -- work around https://github.com/tidyverse/dplyr/pull/7049
- Implement `bind_rows()` to use `reduce(union_all)` under the hood.
- Is there a canonical helper for the `map(paths, fun) %>% bind_rows()` pattern that we can point to in the documentation?

**Comment by krlmlr** [comment]
`bind_rows()` is not a generic, unfortunately. Will solve with documentation.
