### ISSUE TITLE
Can't seem to build the duckplyr package

### ISSUE THREAD

**Issue by Tmonster** [duckdblabs/duckplyr#2]
Hi @krlmlr,

I can't seem to build or test this package. Every time I try to run 
```
# install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))
pak::[pak](http://pak.r-lib.org/reference/pak.html)("duckdblabs/duckplyr")
```
I get the following output 
```R
! Using bundled GitHub PAT. Please add your own PAT using `gitcreds::gitcreds_set()`.
✔ Loading metadata database ... done

→ Will install 1 package.
→ Will download 1 package with unknown size.
+ duckplyr   0.0.1 👷🏻‍♂️🔧 ⬇ (GitHub: be62813)
ℹ Getting 1 pkg with unknown size
✔ Cached copy of duckplyr 0.0.1 (source) is the latest build
✔ No downloads needed, all packages are cached
ℹ Packaging duckplyr 0.0.1
✔ Packaged duckplyr 0.0.1 (702ms)
ℹ Building duckplyr 0.0.1
✖ Failed to build duckplyr 0.0.1
Error:
! error in pak subprocess
Caused by error in `stop_task_build(state, worker)`:
! Failed to build source package 'duckplyr'
Type .Last.error to see the more details.
```

Let me know if you need more information. I ran the initial stops in th my duckdbd directory and the duckply directory

**Comment by Tmonster** [comment]
Nevermind, I think I got it working with the command 
`devtools::install_github("duckdblabs/duckplyr")`

**Comment by krlmlr** [comment]
Thanks. I tried `pak::pak(...)`, works for me 🤷 .

You can also clone the repository and run `R CMD INSTALL .` .

If you need a specific branch or PR and don't want to clone, use, e.g., `devtools::install_github("duckdblabs/duckplyr@f-summarise")` or  `devtools::install_github("duckdblabs/duckplyr#1")` .

**Comment by Tmonster** [comment]
@krlmlr It seems I'm still getting errors so I can't reproduce the exact issue in https://github.com/duckdblabs/duckplyr/pull/1. This is what I'm seeing after running `devtools::install_github("duckdblabs/duckplyr@f-summarise")`
```R
** R
** byte-compile and prepare package for lazy loading
Error: object ‘reframe’ is not exported by 'namespace:dplyr'
Execution halted
ERROR: lazy loading failed for package ‘duckplyr’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/duckplyr’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/1y/_kcy3dfd2q7f7r8k_hyf4k7c0000gr/T//Rtmp3JqVdi/filee3a82c4082ed/duckplyr_0.0.1.tar.gz’ had non-zero exit statu
  ```
I assume it's just something simple regarding the function `reframe`?

**Comment by krlmlr** [comment]
Oh, right, you need the dev version of dplyr 🤦

**Comment by krlmlr** [comment]
We can add it to `DESCRIPTION` so that it's installed automatically. That's what we get for foregoing CI/CD...
