### ISSUE TITLE
make "generated by" comment a bit stricter

### ISSUE THREAD

**Issue by maelle** [duckdblabs/duckplyr#25]
The comment is

```r
# Generated by 02-duckplyr_df-methods.R
```

Does it mean one must not edit the file? If so, why not make it stricter like Rd comments?
- ": do not edit by hand" (just adding this at the end of the first line allows to get the same behavior as for Rd files https://github.com/rstudio/rstudio/pull/2085)

![image](https://github.com/duckdblabs/duckplyr/assets/8360597/3b192840-ff09-422e-b156-1ade2039f1c7)

- where to make edits instead.

**Comment by krlmlr** [comment]
These are supposed to be edited, the generation consists of the script plus the application of a patch.

Needs to be documented.
