### ISSUE TITLE
add support for ASOF LEFT JOIN using join_by(closest())

### ISSUE THREAD

**Issue by rdavis120** [duckdblabs/duckplyr#36]
Now that duckdb 0.8 supports asof joins, it would be great if dplyr verbs could be used to support a "ASOF LEFT JOIN".  I think it would be specific case of dplyr::join_by(closest(date >= date) , also referred to as a "rolling" join in data.table. 

In dplyr it would be this:
```dplyr::left_join(calendar, data, by = dplyr::join_by(closest(date >= date)))```

In duckdb it would be this:
```SELECT calendar.date AS cdate, data.date AS ddate, value FROM calendar ASOF LEFT JOIN data USING(date);```

**Comment by krlmlr** [comment]
Thanks, done now. Does it work for you?
