### ISSUE TITLE
Filters are not pushed into httpfs requests

### ISSUE THREAD

**Issue by Tmonster** [duckdblabs/duckplyr#37]
Just writing down something I noticed that we should fix eventually. 

Duckdb has the ability to query s3 buckets, and push down filters into [hive partitions](https://duckdb.org/docs/guides/import/s3_import.html). Thought this might be a cool feature to test in duckplyr since we export table functions. The s3 bucket I'm testing on contains a copy of the parquet files found here https://github.com/Tmonster/duckplyr_demo/tree/main/taxi-data-2019-partitioned. In total it's about 2.7 GB.

If I only want December data, the query
`select * from read_parquet('s3://duckplyr-demo-taxi-data/taxi-data-2019-partitioned/*/*.parquet', hive_partitioning=TRUE) where month=12` will only download data in the directory month=12

This functionality works with the regular R duckdb package. Steps to reproduce are below. 

First build R with static extensions
```bash
cd duckdb
make clean
GEN=ninja EXTENSION_STATIC_BUILD=1 BUILD_R=1 make
```
When creating a connection, we want to allow unsigned extensions for development purposes
```R
library(duckdb)
set_keys <- "set s3_region='{{region}}';set s3_access_key_id='{{access_key_id}}';set s3_secret_access_key='{{secret_access_key}}';"
DBI::dbExecute(con, set_keys)
[1] 0
con <- DBI::dbConnect(duckdb::duckdb(config=list("allow_unsigned_extensions"="true")))
load_httpfs <- "LOAD '{{home_dir}}/duckdb/build/release/extension/httpfs/httpfs.duckdb_extension'"
DBI::dbExecute(con, load_httpfs)
[1] 0
dbExecute(con, "create table december as select * from read_parquet('s3://duckplyr-demo-taxi-data/taxi-data-2019-partitioned/*/*.parquet', hive_partitioning=TRUE) where month=12")
# [1] 6895933
```

The duckplyr package seems to run out of memory and hit vector exhaustion
```R
library(duckplyr)
# I modified a local version of duckplyr to automatically add the secret key etc.
taxi_data_2019_december <- duckplyr_df_from_file('s3://duckplyr-demo-taxi-data/taxi-data-2019-partitioned/*/*.parquet', 'read_parquet', list(hive_partitioning=TRUE)) |> filter(month == 12)
Error: vector memory exhausted (limit reached?)
```
If the error doesn't occur, the time it takes for the query to complete is noticeably longer than the examples in R or duckdb.

Writing out the query in the relational api works as well.
```R
library(duckdb)
set_keys <- "set s3_region='{{region}}';set s3_access_key_id='{{access_key_id}}';set s3_secret_access_key='{{secret_access_key}}';"
DBI::dbExecute(con, set_keys)
[1] 0
con <- DBI::dbConnect(duckdb::duckdb(config=list("allow_unsigned_extensions"="true")))
load_httpfs <- "LOAD '{{home_dir}}/duckdb/build/release/extension/httpfs/httpfs.duckdb_extension'"
DBI::dbExecute(con, load_httpfs)
DBI::dbExecute(con, "CREATE OR REPLACE MACRO eq(a, b) AS a = b")
all_taxi_data <- duckdb:::rel_from_table_function(con, "read_parquet", list("s3://duckplyr-demo-taxi-data/taxi-data-2019-partitioned/*/*.parquet"), list(hive_partitioning=TRUE))
december_data <- duckdb:::rel_filter(all_taxi_data, list(duckdb:::expr_function("eq", list(duckdb:::expr_reference("month"), duckdb:::expr_constant(12)))))
duckdb:::rel_to_altrep(december_data)
```

Since the raw R package works and the relational package, I think this issue is somewhere in duckplyr

**Comment by krlmlr** [comment]
Thanks. The duckplyr code still looks good to me.

Can you please share the credentials with me so that I can take a look locally?

**Comment by Tmonster** [comment]
If I'm not mistaken, you have an account on the duckdb aws account correct? You should be able to create credentials there and access the s3 bucket described in the example. 
https://docs.aws.amazon.com/powershell/latest/userguide/pstools-appendix-sign-up.html

**Comment by krlmlr** [comment]
I can't repro this with 4f521016a0ff173704d37b7b7808ce752032e677 and duckdb 0.8.1-1 from CRAN. The following works in no time:

``` r
options(conflicts.policy = list(warn = FALSE))
library(duckplyr)
library(dplyr)

# I modified a local version of duckplyr to automatically add the secret key etc.
taxi_data_2019_december <-
  duckplyr_df_from_file("s3://duckplyr-demo-taxi-data/taxi-data-2019-partitioned/*/*.parquet", "read_parquet", list(hive_partitioning = TRUE)) |>
  filter(month == 12) |>
  select(pickup_datetime)

taxi_data_2019_december |>
  duckdb_rel_from_df() |>
  rel_explain()
#> ┌───────────────────────────┐
#> │       READ_PARQUET        │
#> │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
#> │      pickup_datetime      │
#> │   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
#> │           EC: 0           │
#> └───────────────────────────┘

nrow(taxi_data_2019_december)
#> materializing:
#> ---------------------
#> --- Relation Tree ---
#> ---------------------
#> Projection [pickup_datetime as pickup_datetime]
#>   Filter [==("month", 12.0)]
#>     read_parquet(s3://duckplyr-demo-taxi-data/taxi-data-2019-partitioned/*/*.parquet)
#> 
#> ---------------------
#> -- Result Columns  --
#> ---------------------
#> - pickup_datetime (TIMESTAMP)
#> [1] 6895933
```

<sup>Created on 2023-07-19 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Tmonster** [comment]
Interesting, I see the same. I think the difference is that you include the dplyr package. Is there a reason why that also needs to be included?

**Comment by krlmlr** [comment]
`dplyr::filter` is not `stats::filter`, the latter is available by default and probably materializes the entire object.

**Comment by Tmonster** [comment]
That makes sense. So `duckplyr::filter` isn't used because `dplyr::filter` isn't included?

**Comment by krlmlr** [comment]
This should be working now. Please open a new issue if problems persist.
