### ISSUE TITLE
Hash Aggregation does not preserve order

### ISSUE THREAD

**Issue by lnkuiper** [duckdblabs/duckplyr#38]
I'm working on improving DuckDB's hash aggregation, and my CI runs are failing on an R test, `test-rel_api.R`, generated by `05-duckdb-tests.R`, which should not be edited by hand.

This test file includes six test cases that assume order-preserving hash aggregation:
```
"relational count() order-preserving"
"relational count(a) order-preserving"
"relational count(b) order-preserving"
"relational count(g) order-preserving"
"relational count(g, a) order-preserving"
"relational count(b, g) order-preserving"
```

DuckDB's hash aggregation does not preserve order. These test cases have succeeded for now because the tests cases meet two criteria:
1. The input size is less than 120k rows
2. There are less than 10k groups

I have made improvements to DuckDB's hash aggregation. As a result, DuckDB no longer preserves order, even if it meets these two criteria.

I would like to re-generate `test-rel_api.R` without the order-preservation checks for the hash aggregation. How would I go about doing this?

**Comment by krlmlr** [comment]
Thanks for the heads-up. I have found the run: https://github.com/lnkuiper/duckdb/actions/runs/5597155124/jobs/10235135532 .

The tests are there to ensure that duckdb's behavior aligns with duckplyr's expectations. I need to change the expectations (can do this with your branch), and would then submit a PR for these tests.

**Comment by lnkuiper** [comment]
@krlmlr Thanks for the quick response! The expected behavior should be that the values can appear in any order and that the order is non-deterministic due to parallelism.

**Comment by krlmlr** [comment]
We make an effort to keep the output order unchanged here, optionally. We just need to enable it for this particular function.

**Comment by krlmlr** [comment]
I need more time to figure that out. Can you please for now add calls like `skip("https://github.com/duckdblabs/duckplyr/issues/38#issuecomment-1641986295")` at the beginning of the failing tests (even if it says to not edit that file)?

**Comment by krlmlr** [comment]
We no longer rely on sort order after aggregations in this project. I'm submitting https://github.com/krlmlr/duckdb/tree/f-duckplyr-tests as a PR when green, this will fix the tests also with the oocha branch.
