### ISSUE TITLE
Can you explain how you translate R expressions into duckdb syntax?

### ISSUE THREAD

**Issue by etiennebacher** [duckdblabs/duckplyr#40]
Hello, I'm interested in knowing the way you translate R expressions to duckdb syntax. I have a similar task to do in [`tidypolars`](https://github.com/etiennebacher/tidypolars) that aims at providing the `tidyverse` syntax for `polars`. Most functions are implemented now, but I'm not super happy with the way I translate R expressions to polars expressions in `mutate()` and `summarize()`.

Polars expressions are chained with `$`, which gives a sort of R6 syntax. To give you an example, `y = mean(x)` would be `pl$col("x")$mean()$alias("y")` in polars syntax. 

### What I do so far

I have a list of R functions with their equivalent in Polars syntax. Here's what I do so far:

* get the list of expressions in a `mutate`/`summarize` call and deparse them
* for each (deparsed) expression:
  * I get the column names (using `getParsedData`, I extract the `SYMBOL`s that match column names of the data). I wrap each column name in `pl$col()`
  * I extract function calls (still using `getParsedData`), and prefix them with `pl_`
  * in the end, `mean(x)` becomes `pl_mean(pl$col("x"))`
  * internally, I have defined `pl_mean(x)` with the `polars` syntax inside

I also have put some details in [this vignette](https://www.tidypolars.etiennebacher.com/articles/parsing-expressions). 

The main drawback of this approach is that I extract each expression as a string, which means that 1) the code relies on regular expressions and I'm far from being an expert on these, 2) it requires to `eval()` the expressions at the end. I'm not sure if the latter really is a concern, I've seen many times that `eval()` on strings is strongly discouraged but I don't know if it could lead to problematic scenarios here.

In the end, this way works but I'm curious to know if there are some alternatives to have more robust code. I tried a bit to explore the scripts in `tools` and `patch`, but I don't understand at which point you deal with this translation. Do you have some time to explain a bit the process of rewriting expressions in `duckplyr`? Or do you already have something written up somewhere? 

Thank you

**Comment by krlmlr** [comment]
Thanks. The relevant code is in `to_duckdb_expr()`, it will see changes in the coming days.

Please consider reviewing https://adv-r.hadley.nz/translation.html and any preceding chapters from that book you find useful.

**Comment by krlmlr** [comment]
`rel_translate()` is more relevant, `to_duckdb_expr()` converts from our intermediate representation to DuckDB expressions specific to that API.

**Comment by etiennebacher** [comment]
That was extremely helpful, I could rewrite some parts for my use, thanks a lot!
