### ISSUE TITLE
Stabilize rendering of README

### ISSUE THREAD

**Issue by krlmlr** [duckdblabs/duckplyr#62]
We need an output hook (?) that normalizes all `0x.....` strings. Also need to use only queries with stable sort order, or set the `DUCKPLYR_OUTPUT_ORDER` env var to `TRUE`.

**Comment by maelle** [comment]
Notes to self.

What's used in the snapshot test of the same piece of code

```
transform = function(x) gsub("0x[0-9a-f]+", "0xdeadbeef", x),
```

I'm hoping to instead be able to use an [escape hatch / test switch](https://blog.r-hub.io/2023/01/23/code-switch-escape-hatch-test/).

**Comment by maelle** [comment]
:eyes: `"DUCKPLYR_META_SKIP"`

**Comment by maelle** [comment]
The code comes from https://github.com/duckdb/duckdb-r/blob/d243b5301bdca5e642a4579ced6fd7f7b9ded04e/src/relational.cpp#L136

**Comment by maelle** [comment]
Installing duckdb took a while. I'm back to this problem now that it's done and will set a knitr hook for the sake of simplicity since the environment variable wasn't actually the right switch.

**Comment by maelle** [comment]
ouch but the output is from cat()
