### ISSUE TITLE
Save results to Parquet file

### ISSUE THREAD

**Issue by krlmlr** [duckdblabs/duckplyr#87]
Similarly to `df_from_file()`, but the other way.

@Tmonster: Is it realistic to assume that writing straight to Parquet can help conserve memory when processing large datasets? What would it take to provide this functionality in duckdb?

**Comment by Tmonster** [comment]
>  Is it realistic to assume that writing straight to Parquet can help conserve memory when processing large datasets?
Yes, depending on if the connection is in-memory etc.

> What would it take to provide this functionality in duckdb? 
Shouldn't take too long. I am busy with some other projects but will try to get to it soon. Might be nice to demo at the next meeting

**Comment by Tmonster** [comment]
https://github.com/duckdb/duckdb-r/pull/46 should address this

**Comment by Tmonster** [comment]
> @Tmonster: Is it realistic to assume that writing straight to Parquet can help conserve memory when processing large datasets? What would it take to provide this functionality in duckdb?

To answer this however, in my experience, larger than memory datasets cannot be exported to parquet easily. I think it has to do with the fact that all of the table data needs to be in memory in order to calculate what the metadata needed a the end of the parquet file etc. To get around this you can just export to CSV, or just store data in a separate DuckDB connection

**Comment by krlmlr** [comment]
Interesting. So the memory required is at least the size of each partition in a partitioned Parquet file? Should we support passing partitioning options to `rel_to_parquet()` ?

**Comment by Tmonster** [comment]
Yes, we should support passing partitioning options to `rel_to_parquet`. We are coming up on a bug fix release soon, so I can look into it then

**Comment by krlmlr** [comment]
I'll look into memory requirements with

```
set memory_limit='8MB'
pragma temp_directory='/tmp'
pragma preserve_insertion_order=false
```
