### ISSUE TITLE
Current test errors

### ISSUE THREAD

**Issue by maelle** [duckdblabs/duckplyr#9]
@krlmlr I installed dev dplyr as I saw there was some discussion of this here. How many of the failures below are known problems? Could you open one or a few issues with what problems you already expected? (for instance, the methods errors are not surprising if I follow correctly, and would be one thing to fix)

[duckplyr-test-results.md](https://github.com/duckdblabs/duckplyr/files/11530938/duckplyr-test-results.md)

**Comment by maelle** [comment]
For instance I see https://github.com/tidyverse/dplyr/pull/6596 that looks related to test-distinct failure? (where attributes are not kept)

**Comment by krlmlr** [comment]
duckdb >= 0.8.0 .

**Comment by maelle** [comment]
aaah indeed, that's now better. :smile_cat:
