### ISSUE TITLE
Can't `df_from_file` automatically determine the table function from the file extension?

### ISSUE THREAD

**Issue by eitsupi** [duckdblabs/duckplyr#96]
I am wondering if it is possible to automatically set the function in cases where the file extension is properly set. Like:

- `foo.parquet` -> `"read_parquet"`
- `foo.csv`, `foo.CSV` -> `"read_csv_auto"`

**Comment by krlmlr** [comment]
Good idea, thanks!

**Comment by krlmlr** [comment]
I'll go with new specialized functions `(duckplyr_)?df_from_(csv|parquet)` .
